Rails.application.routes.draw do
  get 'wallets/new'
  get 'wallets/create'
  get 'wallets/edit'
  get 'wallets/update'
  get 'wallets/destroy'
  get 'wallets/index'
  get 'wallets/show'
  get 'sales/new'
  get 'sales/create'
  get 'sales/edit'
  get 'sales/update'
  get 'sales/destroy'
  get 'sales/index'
  get 'sales/show'
  get 'projects/new'
  get 'projects/create'
  get 'projects/edit'
  get 'projects/update'
  get 'projects/destroy'
  get 'projects/index'
  get 'projects/show'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  get 'products/index'
  get 'products/show'
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/index'
  get 'users/show'
  resources :sales
  resources :products
  resources :wallets
  resources :projects
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
